name: getsecure
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.6.2
  flutter_hooks: ^0.20.5
  cupertino_icons: ^1.0.8
  hooks_riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  material: ^1.0.0+2
  footer: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Roboto-Bold.ttf
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
